# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('base_currency', models.CharField(max_length=256)),
                ('second_currency', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
