# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pairs',
            new_name='Pair',
        ),
    ]
